In [1]:
import pandas as pd 
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [2]:
data_df = pd.read_csv("mushrooms.csv",index_col=False)

In [3]:
data_df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [4]:
label = data_df['class']
label.replace('p',0,inplace=True)
label.replace('e',1,inplace=True)
label.head()

0    0
1    1
2    1
3    0
4    1
Name: class, dtype: int64

In [5]:
features = data_df.drop(columns=['class'])
features.head()

,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,x,s,n,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,k,s,u
1,x,s,y,t,a,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,g
2,b,s,w,t,l,f,c,b,n,e,...,s,w,w,p,w,o,p,n,n,m
3,x,y,w,t,p,f,c,n,n,e,...,s,w,w,p,w,o,p,k,s,u
4,x,s,g,f,n,f,w,b,k,t,...,s,w,w,p,w,o,e,n,a,g

In [6]:
features_number = pd.get_dummies(features)
print(features_number.shape)
features_number.head()

(8124, 117)

,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_f,cap-surface_g,cap-surface_s,cap-surface_y,...,population_s,population_v,population_y,habitat_d,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
0,0,0,0,0,0,1,0,0,1,0,...,1,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
2,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,1,0,0,0,1,...,1,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0

In [7]:
features_values = features_number.values.astype('float32')
label_values = label.values.astype('float32')

In [8]:
features_train, features_test,label_train,label_test = train_test_split\
(features_values, label_values, test_size=0.2)
features_train, features_validation,label_train,label_validation = train_test_split\
(features_train, label_train, test_size=0.2)

In [9]:
l0 = keras.layers.Dense(32, input_shape=(117,))
l1 = keras.layers.Dense(20, activation=tf.nn.relu)
l2 = keras.layers.Dense(2, activation='softmax')

WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

In [10]:
model = keras.Sequential([l0,l1,l2])

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 32)                3776
_________________________________________________________________
dense_1 (Dense)              (None, 20)                660
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 42
=================================================================
Total params: 4,478
Trainable params: 4,478
Non-trainable params: 0
_________________________________________________________________

In [12]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['acc'])

In [13]:
history = model.fit(features_train,label_train,epochs=10,validation_data=(features_validation,label_validation))

Train on 5199 samples, validate on 1300 samples
Epoch 1/10
5199/5199 [==============================] - 0s 88us/sample - loss: 0.1337 - acc: 0.9554 - val_loss: 0.0256 - val_acc: 0.9969
Epoch 2/10
5199/5199 [==============================] - 0s 55us/sample - loss: 0.0119 - acc: 0.9987 - val_loss: 0.0067 - val_acc: 0.9992
Epoch 3/10
5199/5199 [==============================] - 0s 53us/sample - loss: 0.0036 - acc: 1.0000 - val_loss: 0.0028 - val_acc: 0.9992
Epoch 4/10
5199/5199 [==============================] - 0s 57us/sample - loss: 0.0017 - acc: 1.0000 - val_loss: 0.0016 - val_acc: 1.0000
Epoch 5/10
5199/5199 [==============================] - 0s 53us/sample - loss: 8.8602e-04 - acc: 1.0000 - val_loss: 0.0010 - val_acc: 1.0000
Epoch 6/10
5199/5199 [==============================] - 0s 54us/sample - loss: 5.8225e-04 - acc: 1.0000 - val_loss: 6.9046e-04 - val_acc: 1.0000
Epoch 7/10
5199/5199 [==============================] - 0s 69us/sample - loss: 3.8816e-04 - acc: 1.0000 - val_loss: 6.2583e-04 - val_acc: 1.0000
Epoch 8/10
5199/5199 [==============================] - 0s 64us/sample - loss: 2.7961e-04 - acc: 1.0000 - val_loss: 4.1163e-04 - val_acc: 1.0000
Epoch 9/10
5199/5199 [==============================] - 0s 63us/sample - loss: 2.1311e-04 - acc: 1.0000 - val_loss: 3.2765e-04 - val_acc: 1.0000
Epoch 10/10
5199/5199 [==============================] - 0s 64us/sample - loss: 1.6077e-04 - acc: 1.0000 - val_loss: 2.8671e-04 - val_acc: 1.0000

In [14]:
predicted_feature = model.predict(features_test)
model.evaluate(features_test,label_test)

1625/1625 [==============================] - 0s 26us/sample - loss: 2.1275e-04 - acc: 1.0000

[0.0002127510579258132, 1.0]